# Generated by Django 4.2.3 on 2023-08-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.IntegerField(choices=[(1, 'นาย'), (2, 'นางสาว'), (3, 'นาง')])),
                ('std_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
